import { z } from "zod";

/**
 * data_xplorer/google-news-scraper-fast — actor input schema, scaffolded from the actor's PUBLISHED
 * input schema (GET /v2/acts/data_xplorer~google-news-scraper-fast/builds/default →
 * actorDefinition.input) on 2026-09-05 via scripts/apify-scaffold.ts; curated
 * by hand thereafter (re-run the script to refresh; the live-gated
 * schema-drift test flags divergence). Non-strict by policy: the actor
 * accepts supersets — unknown fields pass through.
 */
export const zGoogleNewsScraperFastBody = z.object({
    "keywords": z.array(z.any()).describe(
        "List of keywords to search for. You can use Google News search operators: - Use '-' to exclude words (e.g. 'bitcoin -ethereum') - Use 'site:' to filter by specific website (e.g. 'bitcoin site:cnn.com') - Use 'OR' to search for multiple terms (e.g. 'bitcoin OR ethereum') - Use quotes for exact mat...",
    ).optional(),
    "topics": z.array(
        z.enum([
            "WORLD",
            "NATION",
            "BUSINESS",
            "TECHNOLOGY",
            "ENTERTAINMENT",
            "SPORTS",
            "SCIENCE",
            "HEALTH",
        ]),
    ).describe("Select one or more predefined Google News topics to scrape.")
        .optional(),
    "topicUrls": z.array(z.any()).describe(
        "Provide custom Google News topic or section URLs to scrape. Useful for niche topics not in the predefined list. Example: https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB",
    ).optional(),
    "maxArticles": z.number().int().min(0).describe(
        "Maximum number of news to extract per keyword or topic (0 = no limit)",
    ).optional(),
    "timeframe": z.enum(["1h", "1d", "7d", "30d", "1y", "all"]).describe(
        "Time period for the news search. Note: this filter applies mainly to keyword searches. Topic pages return their own curated results.",
    ).optional(),
    "region_language": z.enum([
        "US:en",
        "SK:sk",
        "AU:en",
        "BW:en",
        "CA:en",
        "ET:en",
        "GH:en",
        "IN:en",
        "ID:en",
        "IE:en",
        "IL:en",
        "KE:en",
        "LV:en",
        "MY:en",
        "NA:en",
        "NZ:en",
        "NG:en",
        "PK:en",
        "PH:en",
        "SG:en",
        "ZA:en",
        "TZ:en",
        "UG:en",
        "GB:en",
        "ZW:en",
        "ID:id",
        "CZ:cs",
        "DE:de",
        "AT:de",
        "CH:de",
        "AR:es-419",
        "CL:es-419",
        "CO:es-419",
        "CU:es-419",
        "ES:es",
        "US:es-419",
        "MX:es-419",
        "PE:es-419",
        "VE:es-419",
        "BE:fr",
        "CA:fr",
        "FR:fr",
        "MA:fr",
        "SN:fr",
        "CH:fr",
        "IT:it",
        "LV:lv",
        "LT:lt",
        "HU:hu",
        "BE:nl",
        "NL:nl",
        "NO:no",
        "PL:pl",
        "BR:pt-419",
        "PT:pt-150",
        "RO:ro",
        "SI:sl",
        "SE:sv",
        "VN:vi",
        "TR:tr",
        "GR:el",
        "BG:bg",
        "RU:ru",
        "UA:ru",
        "RS:sr",
        "UA:uk",
        "IL:he",
        "AE:ar",
        "SA:ar",
        "LB:ar",
        "EG:ar",
        "IN:mr",
        "IN:hi",
        "BD:bn",
        "IN:bn",
        "IN:ta",
        "IN:te",
        "IN:ml",
        "TH:th",
        "CN:zh-Hans",
        "TW:zh-Hant",
        "HK:zh-Hant",
        "JP:ja",
        "KR:ko",
    ]).describe("Region and language for news search").optional(),
    "decodeUrls": z.boolean().describe(
        "If enabled, decodes Google News URLs to get the original article URLs. Note: This will significantly slow down the scraping process as each URL needs to be decoded individually.",
    ).optional(),
    "extractDescriptions": z.boolean().describe(
        "If enabled, extracts the meta description from each article page. Note: This will significantly slow down the scraping process.",
    ).optional(),
    "extractImages": z.boolean().describe(
        "Fetches the og:image from each article page when no image is available (mainly for RSS/topic results). When this option is not explicitly set, images are extracted by default. Toggle OFF to skip image extraction and speed up scraping.",
    ).optional(),
    "proxyConfiguration": z.record(z.string(), z.any()).describe(
        "Configure Apify Proxy. Residential proxies recommended for best results.",
    ).optional(),
});
