import { z } from "zod";

/**
 * apimint/google-ads-transparency-scraper — actor input schema, scaffolded from the actor's PUBLISHED
 * input schema (GET /v2/acts/apimint~google-ads-transparency-scraper/builds/default →
 * actorDefinition.input) on 2026-10-10 via scripts/apify-scaffold.ts; curated
 * by hand thereafter (re-run the script to refresh; the drift suite
 * flags divergence — deno task drift). Non-strict by policy: the actor
 * accepts supersets — unknown fields pass through.
 */
export const zGoogleAdsTransparencyScraperBody = z.object({
    searchTerms: z.array(z.string()).describe(
        'A brand or keyword, such as "plumber" or "nike". Google matches it against advertiser names and website domains (not ad text), then the Actor pulls every ad of the matching advertisers. Up to "Max advertisers per search term" advertisers per term.',
    ).optional(),
    domains: z.array(z.string()).describe(
        "Websites whose ads you want, such as hubspot.com. Includes other advertisers whose ads point to the domain (resellers, agencies). https://, www. and paths are removed for you.",
    ).optional(),
    advertiserIds: z.array(z.string()).describe(
        "Google advertiser IDs, which start with AR (AR16735076323512287233 is Nike, Inc.). You find them in the Transparency Center URL of an advertiser.",
    ).optional(),
    startUrls: z.array(z.string()).describe(
        "Any adstransparency.google.com URL: an advertiser page, a domain search or a single ad. The URL's region, format and platform settings are used for that URL.",
    ).optional(),
    region: z.enum([
        "anywhere",
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "VG",
        "BN",
        "BG",
        "BF",
        "BI",
        "KH",
        "CM",
        "CA",
        "CV",
        "BQ",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UM",
        "VI",
        "UG",
        "UA",
        "AE",
        "GB",
        "US",
        "UY",
        "UZ",
        "VU",
        "VA",
        "VE",
        "VN",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW",
    ]).describe(
        'Only ads shown in this country. "Anywhere" returns ads from every country.',
    ).optional(),
    platform: z.enum(["any", "search", "youtube", "maps", "shopping", "play"])
        .describe("Only ads shown on this Google platform.").optional(),
    format: z.enum(["any", "text", "image", "video"]).describe(
        "Only text, image or video ads.",
    ).optional(),
    dateFrom: z.string().describe(
        'Only ads shown on or after this date: YYYY-MM-DD (2026-09-01) or a relative period such as "30 days". Leave empty for all time.',
    ).optional(),
    dateTo: z.string().describe(
        "Only ads shown on or before this date, same format. Leave empty for today.",
    ).optional(),
    maxAdsPerTarget: z.number().int().min(0).describe(
        "Stop after this many ads for each search term, domain, advertiser or URL. 0 means no limit.",
    ).optional(),
    maxAds: z.number().int().min(0).describe(
        "Stop the whole run after this many ads. 0 means no limit. The run also stops at your maximum cost per run.",
    ).optional(),
    maxAdvertisersPerTerm: z.number().int().min(1).max(50).describe(
        "How many matching advertisers (and matching domains) to scrape for each search term.",
    ).optional(),
    termMustAppearInAd: z.boolean().describe(
        "Keep only ads whose headline, description, display URL or sitelinks contain the search term. Ads with no readable copy are left out.",
    ).optional(),
    includeAdDetails: z.boolean().describe(
        "All saved versions of each ad, the countries where it ran with first and last dates, and EU reach and targeting. Turn off for a faster list-only run.",
    ).optional(),
    extractTextFromScreenshots: z.boolean().describe(
        "Google stores most text ads only as an image. This reads the headline, description, display URL and sitelinks from it. Included in the price. Free Apify plan: standard OCR (Tesseract). Paid plans: an AI model reads every screenshot (more accurate, faster).",
    ).optional(),
    extractTextFromAllVersions: z.boolean().describe(
        "Also read the headline, description and display URL of every saved version of a text ad (in variations). Slower: most ads have 3–5 versions. The main ad copy is read either way. Same price.",
    ).optional(),
    onlyNewAds: z.boolean().describe(
        "Monitoring mode: skip ads already returned by earlier runs for the same target and filters. Skipped ads are not charged. Use it with a schedule.",
    ).optional(),
    proxyConfiguration: z.record(z.string(), z.any()).describe(
        "Used for Google's ad-listing requests. If Google keeps blocking, the Actor switches to residential proxies by itself.",
    ).optional(),
});
