import { z } from "zod";

/**
 * damilo/google-maps-scraper — actor input schema, scaffolded from the actor's PUBLISHED
 * input schema (GET /v2/acts/damilo~google-maps-scraper/builds/default →
 * actorDefinition.input) on 2026-09-03 via scripts/apify-scaffold.ts; curated
 * by hand thereafter (re-run the script to refresh; the live-gated
 * schema-drift test flags divergence). Non-strict by policy: the actor
 * accepts supersets — unknown fields pass through.
 */
export const zGoogleMapsScraperBody = z.object({
    "query": z.string().describe("Define search query"),
    "location": z.string().describe("Define location"),
    "place_id": z.string().describe("Google Maps Place ID for the location")
        .optional(),
    "cid": z.string().describe(
        "Search by Google Maps CID (Customer Identification)",
    ).optional(),
    "language": z.enum([
        "af",
        "ak",
        "sq",
        "am",
        "ar",
        "hy",
        "az",
        "eu",
        "be",
        "bem",
        "bn",
        "bh",
        "xx-bork",
        "bs",
        "br",
        "bg",
        "km",
        "ca",
        "chr",
        "ny",
        "zh-cn",
        "zh-tw",
        "co",
        "hr",
        "cs",
        "da",
        "nl",
        "xx-elmer",
        "en",
        "eo",
        "et",
        "ee",
        "fo",
        "tl",
        "fi",
        "fr",
        "fy",
        "gaa",
        "gl",
        "ka",
        "de",
        "el",
        "gn",
        "gu",
        "xx-hacker",
        "ht",
        "ha",
        "haw",
        "iw",
        "hi",
        "hu",
        "is",
        "ig",
        "id",
        "ia",
        "ga",
        "it",
        "ja",
        "jw",
        "kn",
        "kk",
        "rw",
        "rn",
        "xx-klingon",
        "kg",
        "ko",
        "kri",
        "ku",
        "ckb",
        "ky",
        "lo",
        "la",
        "lv",
        "ln",
        "lt",
        "loz",
        "lg",
        "ach",
        "mk",
        "mg",
        "ms",
        "ml",
        "mt",
        "mi",
        "mr",
        "mfe",
        "mo",
        "mn",
        "sr-ME",
        "ne",
        "pcm",
        "nso",
        "no",
        "nn",
        "oc",
        "or",
        "om",
        "ps",
        "fa",
        "xx-pirate",
        "pl",
        "pt",
        "pt-br",
        "pt-pt",
        "pa",
        "qu",
        "ro",
        "rm",
        "nyn",
        "ru",
        "gd",
        "sr",
        "sh",
        "st",
        "tn",
        "crs",
        "sn",
        "sd",
        "si",
        "sk",
        "sl",
        "so",
        "es",
        "es-419",
        "su",
        "sw",
        "sv",
        "tg",
        "ta",
        "tt",
        "te",
        "th",
        "ti",
        "to",
        "lua",
        "tum",
        "tr",
        "tk",
        "tw",
        "ug",
        "uk",
        "ur",
        "uz",
        "vi",
        "cy",
        "wo",
        "xh",
        "yi",
        "yo",
        "zu",
    ]).describe("The language to search in.").optional(),
    "max_results": z.number().int().describe(
        "The maximum number of results to scrape.",
    ).optional(),
});
