import { z } from "zod";

/**
 * apify/facebook-pages-scraper — dataset ITEM schema, scaffolded from the actor's
 * PUBLISHED storages.dataset.fields on 2026-09-10 via
 * scripts/apify-scaffold.ts. Passthrough DOCUMENTATION (design D29):
 * non-strict, every field optional ("required" stripped) — output
 * validation can never fail a paid run over vendor drift; the drift
 * suite reports field additions/removals informationally.
 */
export const zFacebookPagesScraperOutputItem = z.object({
    facebookUrl: z.any().describe("URL of the Facebook page that was scraped.")
        .optional(),
    pageId: z.any().describe("Unique Facebook page ID.").optional(),
    pageUrl: z.any().describe("URL of the Facebook page.").optional(),
    title: z.any().describe("Name of the Facebook page.").optional(),
    categories: z.any().describe(
        "Categories or types associated with the page.",
    ).optional(),
    info: z.any().describe(
        "General information lines about the page (e.g. likes count, description).",
    ).optional(),
    likes: z.any().describe("Number of people who like the page.").optional(),
    followers: z.any().describe("Number of followers of the page.").optional(),
    rating: z.any().describe("Average star rating of the page.").optional(),
    email: z.any().describe("Contact email address of the page.").optional(),
    phone: z.any().describe("Contact phone number of the page.").optional(),
    address: z.any().describe("Physical address of the business.").optional(),
    website: z.any().describe("Website URL linked on the page.").optional(),
    websites: z.any().describe("All website URLs linked on the page.")
        .optional(),
    messenger: z.any().describe("Messenger URL for the page.").optional(),
    intro: z.any().describe("Short introductory text from the page profile.")
        .optional(),
    priceRange: z.any().describe("Price range indicator for the business.")
        .optional(),
    services: z.any().describe("Services offered by the business.").optional(),
    alternativeSocialMedia: z.any().describe(
        "Links to other social media accounts.",
    ).optional(),
    wifi: z.any().describe("Wi-Fi availability information.").optional(),
    payment: z.any().describe("Accepted payment methods.").optional(),
    posts: z.any().describe("Recent posts from the page.").optional(),
    personalProfile: z.any().describe(
        "Personal profile data (when the URL is a personal profile, not a page).",
    ).optional(),
    autoGeneratedPage: z.any().describe(
        "Data for auto-generated Facebook pages.",
    ).optional(),
});
/** Tolerant by construction: an item that drifts off the documented
 *  shape still passes as a plain object — validation can NEVER fail a
 *  paid run; the typed branch is the documentation. */
export const zFacebookPagesScraperOutput = z.array(
    zFacebookPagesScraperOutputItem.or(z.record(z.string(), z.unknown())),
);
