import { z } from "zod";

/**
 * apidojo/tweet-scraper — actor input schema, scaffolded from the actor's PUBLISHED
 * input schema (GET /v2/acts/apidojo~tweet-scraper/builds/default →
 * actorDefinition.input) on 2026-09-03 via scripts/apify-scaffold.ts; curated
 * by hand thereafter (re-run the script to refresh; the live-gated
 * schema-drift test flags divergence). Non-strict by policy: the actor
 * accepts supersets — unknown fields pass through.
 */
export const zTweetScraperBody = z.object({
    "startUrls": z.array(z.any()).describe(
        "Twitter (X) URLs. Paste the URLs and get the results immediately. Tweet, Profile, Search or List URLs are supported.",
    ).optional(),
    // curated: stringList editors — items are strings (startUrls left loose:
    // the actor accepts both bare URLs and {url} objects)
    "searchTerms": z.array(z.string()).describe(
        "Search terms you want to search from Twitter (X). You can refer to https://github.com/igorbrigadir/twitter-advanced-search.",
    ).optional(),
    "twitterHandles": z.array(z.string()).describe(
        "Twitter handles that you want to search on Twitter (X)",
    ).optional(),
    "conversationIds": z.array(z.string()).describe(
        "Conversation IDs that you want to search on Twitter (X)",
    ).optional(),
    "maxItems": z.number().int().describe(
        "Maximum number of items that you want as output.",
    ).optional(),
    "sort": z.enum(["Top", "Latest", "Latest + Top"]).describe(
        "Sorts search results. If you are getting low results, try Top instead of Latest. Latest + Top runs both simultaneously to maximize results but may return some duplicate tweets.",
    ).optional(),
    "tweetLanguage": z.enum([
        "ab",
        "aa",
        "af",
        "ak",
        "sq",
        "am",
        "ar",
        "an",
        "hy",
        "as",
        "av",
        "ae",
        "ay",
        "az",
        "bm",
        "ba",
        "eu",
        "be",
        "bn",
        "bi",
        "bs",
        "br",
        "bg",
        "my",
        "ca",
        "ch",
        "ce",
        "ny",
        "zh",
        "cu",
        "cv",
        "kw",
        "co",
        "cr",
        "hr",
        "cs",
        "da",
        "dv",
        "nl",
        "dz",
        "en",
        "eo",
        "et",
        "ee",
        "fo",
        "fj",
        "fi",
        "fr",
        "fy",
        "ff",
        "gd",
        "gl",
        "lg",
        "ka",
        "de",
        "el",
        "kl",
        "gn",
        "gu",
        "ht",
        "ha",
        "he",
        "hz",
        "hi",
        "ho",
        "hu",
        "is",
        "io",
        "ig",
        "id",
        "ia",
        "ie",
        "iu",
        "ik",
        "ga",
        "it",
        "ja",
        "jv",
        "kn",
        "kr",
        "ks",
        "kk",
        "km",
        "ki",
        "rw",
        "ky",
        "kv",
        "kg",
        "ko",
        "kj",
        "ku",
        "lo",
        "la",
        "lv",
        "li",
        "ln",
        "lt",
        "lu",
        "lb",
        "mk",
        "mg",
        "ms",
        "ml",
        "mt",
        "gv",
        "mi",
        "mr",
        "mh",
        "mn",
        "na",
        "nv",
        "nd",
        "nr",
        "ng",
        "ne",
        "no",
        "nb",
        "nn",
        "ii",
        "oc",
        "oj",
        "or",
        "om",
        "os",
        "pi",
        "ps",
        "fa",
        "pl",
        "pt",
        "pa",
        "qu",
        "ro",
        "rm",
        "rn",
        "ru",
        "se",
        "sm",
        "sg",
        "sa",
        "sc",
        "sr",
        "sn",
        "sd",
        "si",
        "sk",
        "sl",
        "so",
        "st",
        "es",
        "su",
        "sw",
        "ss",
        "sv",
        "tl",
        "ty",
        "tg",
        "ta",
        "tt",
        "te",
        "th",
        "bo",
        "ti",
        "to",
        "ts",
        "tn",
        "tr",
        "tk",
        "tw",
        "ug",
        "uk",
        "ur",
        "uz",
        "ve",
        "vi",
        "vo",
        "wa",
        "cy",
        "wo",
        "xh",
        "yi",
        "yo",
        "za",
        "zu",
    ]).describe(
        "Restricts tweets to the given language, given by an ISO 639-1 code.",
    ).optional(),
    "onlyVerifiedUsers": z.boolean().describe(
        "If selected, only returns tweets by users who are verified.",
    ).optional(),
    "onlyTwitterBlue": z.boolean().describe(
        "If selected, only returns tweets by users who are Twitter Blue subscribers.",
    ).optional(),
    "onlyImage": z.boolean().describe(
        "If selected, only returns tweets that contain images.",
    ).optional(),
    "onlyVideo": z.boolean().describe(
        "If selected, only returns tweets that contain videos.",
    ).optional(),
    "onlyQuote": z.boolean().describe(
        "If selected, only returns tweets that are quotes.",
    ).optional(),
    "author": z.string().describe(
        "Returns tweets sent by the given user. It should be a Twitter (X) Handle.",
    ).optional(),
    "inReplyTo": z.string().describe(
        "Returns tweets that are replies to the given user. It should be a Twitter (X) Handle.",
    ).optional(),
    "mentioning": z.string().describe(
        "Returns tweets mentioning the given user. It should be a Twitter (X) Handle.",
    ).optional(),
    "geotaggedNear": z.string().describe(
        "Returns tweets sent near the given location.",
    ).optional(),
    "withinRadius": z.string().describe(
        "Returns tweets sent within the given radius of the given location.",
    ).optional(),
    "geocode": z.string().describe(
        "Returns tweets sent by users located within a given radius of the given latitude/longitude.",
    ).optional(),
    "placeObjectId": z.string().describe(
        "Returns tweets tagged with the given place.",
    ).optional(),
    "minimumRetweets": z.number().int().describe(
        "Returns tweets with at least the given number of retweets.",
    ).optional(),
    "minimumFavorites": z.number().int().describe(
        "Returns tweets with at least the given number of favorites.",
    ).optional(),
    "minimumReplies": z.number().int().describe(
        "Returns tweets with at least the given number of replies.",
    ).optional(),
    "start": z.string().describe("Returns tweets sent after the given date.")
        .optional(),
    "end": z.string().describe("Returns tweets sent before the given date.")
        .optional(),
    "includeSearchTerms": z.boolean().describe(
        "If selected, a field will be added to each tweets about the search term that was used to find it.",
    ).optional(),
    "customMapFunction": z.string().describe(
        "Function that takes each of the objects as argument and returns data that will be mapped by the function itself. This function is not intended for filtering, please don't use it for filtering purposes or you will get banned automatically.",
    ).optional(),
});
